### PR TITLE
LDpred2 imputation

### PR DESCRIPTION
**Pull request by deepchocolate**
Fixes one part of #130. Closing #138 

Changes proposed in this pull request:

- Added an imputation script `usecases/LDpred2/imputeGenotypes.R`. Using `bigsnpr::fastImputeSimple` one can choose one of these methods, but I've also added zero "imputation" as described in the docs for this function.
- Changed the allele flipping in `ldpred2.R` and `calculateLD.R` as described in #124 
- Removed `--geno-impute`from `ldpred2.R`. `--geno-impute-zero` can be passed instead.
- Moved functionality into a separate script `usecases/LDpred2/fun.R` to enable reuse and improved testing `LDpred2_example/unittests/fun.R`.

## Before submitting

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [x] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [x] If this PR fixes a bug, I've added a test that will fail without my fix.
- [x] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

### CODE REVIEW

**Comment by deepchocolate** [comment]
@ofrei @espenhgn I tried adding `fastImpute` (in addition to `fastImputeSimple`), but this depends on `xgboost` (there's an R-package for it). However, I only get errors when trying to use it. Shall I stick with the simple?

**Comment by espenhgn** [comment]
> @ofrei @espenhgn I tried adding `fastImpute` (in addition to `fastImputeSimple`), but this depends on `xgboost` (there's an R-package for it). However, I only get errors when trying to use it. Shall I stick with the simple?

I'm sure we can include `xgboost` in the `r.sif` build if this fixes the issue. Perhaps a specific version of this package is required for `fastImpute`?

**Comment by deepchocolate** [comment]
> > @ofrei @espenhgn I tried adding `fastImpute` (in addition to `fastImputeSimple`), but this depends on `xgboost` (there's an R-package for it). However, I only get errors when trying to use it. Shall I stick with the simple?
> 
> I'm sure we can include `xgboost` in the `r.sif` build if this fixes the issue. Perhaps a specific version of this package is required for `fastImpute`?

I'll stick with `fastImputeSimple` for now as there are some other isues with the scripts, that needs a fix.

**Review by espenhgn — CHANGES_REQUESTED** [review]
Thanks a lot! I encountered some minor issues which were easily resolved (locally), as commented. Shall I push these directly? Other than that:
- in the LDpred2/README.md height example, add the line `$RSCRIPT imputeGenotypes.R --impute-simple mean0 --geno-file-rds $fileGenoRDS` after creating `$fileGenoRDS` itself. Otherwise it won't run.
- It was my bad suggestion to call the test directory for `LDpred2_example`. Perhaps this can by renamed `LDpred2_test` in this PR?

**Comment by deepchocolate** [comment]
@espenhgn I think I've addressed all points. I renamed `usecases/LDpred2_example` to `usecases/LDpred2_test` as you suggested

**Review by espenhgn — APPROVED** [review]
Pushed a small unzip fix to /LDpred2_test/run.sh. Looks good to me!

**Comment by deepchocolate** [comment]
> Pushed a small unzip fix to /LDpred2_test/run.sh. Looks good to me!

Great, thanks!

**Comment by deepchocolate** [comment]
@ofrei Are you ok with merging this?

**Comment by deepchocolate** [comment]
@espenhgn Shall I merge this or wait for an approval from @ofrei aswell?

**Comment by espenhgn** [comment]
> @espenhgn Shall I merge this or wait for an approval from @ofrei aswell?

No need to wait for @ofrei. Just go ahead and squash-merge this one :)

**Comment by espenhgn** [comment]
Btw., it's fine if you merge this first. I expect a small conflict with #141 that I can fix before that one is merged.

**Pull request merged**
