### PR TITLE
some changelog/readme updates for v1.1

### PR DESCRIPTION
**Pull request by espenhgn**
Changelog/Readme updates for #96, which should've been included with PR #97

Changes proposed in this pull request:

- Copy container-software table from `src/README` to `CHANGELOG`. 

## Before submitting

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

### CODE REVIEW

**Comment by ofrei** [comment]
@espenhgn By the end of today I'm hoping to split out MAGMA, LAVA reference to a separate repo, and also move away some other .sif files that aren't a core part of the comorment containers.  I'll will also rebase this branch once it's done.

**Comment by espenhgn** [comment]
> @espenhgn By the end of today I'm hoping to split out MAGMA, LAVA reference to a separate repo, and also move away some other .sif files that aren't a core part of the comorment containers. I'll will also rebase this branch once it's done.

Hi @ofrei. In which order shall we have this? If the v1.1 release does not include MAGMA, LAVA, etc., as you mention, that'd be fine by me. I'd merge this now anyway if you'd give the thumbs up :)

**Review by ofrei — APPROVED** [review]
@espenhgn I rebased and made a [minor change1](https://github.com/comorment/containers/commit/7e1314b38b3f5876209addfb5e320fd24bd683d3) and [minor change2](https://github.com/comorment/containers/commit/618436676479f44fe0f26272f8d94b8d6d5587e7) in the CHANGELOG due to rebase. These are pushed to https://github.com/comorment/containers/tree/fix-96-additions-v2 branch. Please merge that branch or "git cherry-pick" those two commits.

**Comment by espenhgn** [comment]
@ofrei: Fyi, I've deleted the `fix-96-additions-v2` branch on the remote.

**Pull request merged**
