### PR TITLE
`r.sif`: add R `bigsnpr` and related tools for LDpred2 analysis

### LINKED ISSUE #90: `r.sif`: add `bigsnpr` and related tools for LDpred2 analysis
**Describe the solution you'd like**
For Issue #17, add misc. R packages including `bigsnpr`, tests, simple ldpred2.Rmd example from the https://github.com/comorment/ldpred2 repository here.

### PR DESCRIPTION
**Pull request by espenhgn**
Fixes #90

Changes proposed in this pull request:

- Adds additional R packages and usecase-files for LDpred2 analysis from https://github.com/comorment/ldpred2. Also, libraries imported by new R files in the [deepchocolate/ldpred2](https://github.com/comorment/containers/tree/deepchocolate/ldpred2) branch are present.

Note, I added the usecase files as `ldpred2_tmp` as I think they will be superseded by those of branch [deepchocolate/ldpred2](https://github.com/comorment/containers/tree/deepchocolate/ldpred2) by @deepchocolate. When they are no longer needed, they can be removed I think. 
Should add that this edit only increases the size of the built container by about 100MB, from 1.4GB. 

## Before submitting

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [x] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [x] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

### CODE REVIEW

**Comment by espenhgn** [comment]
@ofrei, @deepchocolate, are you fine with this?

**Review by ofrei — APPROVED** [review]
@espenhgn looks great, thanks for including bigsnpr in R.sif!
Could you also commit into our repository the ldpred2.R and run_ldpred2.sh scripts made by @deepchocolate ? The scripts from here: https://github.com/comorment/containers/commit/33698fb4bd132eb2c564749712a0bf4c2d1c80fb
    As for impute.R, I think we could switch to plink's https://www.cog-genomics.org/plink/1.9/data#fill_missing_a2 . This options works like this:
```
plink --bfile <bfile_in> --fill-missing-a2 --make-bed --out <bfile_out>
```

**Comment by espenhgn** [comment]
Hi @ofrei. I can include @deepchocolate's files of course. If you both agree, I can merge that branch into this and move the .R and .sh files where I want them in order to keep the contributions tracked.

**Comment by deepchocolate** [comment]
The only thing I didn't see that I know is needed for my R-script is the R-package argparser. Otherwise it looks great!

**Comment by espenhgn** [comment]
> The only thing I didn't see that I know is needed for my R-script is the R-package argparser. Otherwise it looks great!

Sorry, forgot to push this last minute change. `argparser` should be installed: https://github.com/comorment/containers/pull/91/files#diff-adcb955b173d581f71077f92f6a1872edb47f4f0dc61e0b23f3372a7d0dbe7fe

**Comment by espenhgn** [comment]
@deepchocolate , I just have a question: This file `Height.gwas.txt` referenced on line https://github.com/comorment/containers/blob/33698fb4bd132eb2c564749712a0bf4c2d1c80fb/tests/ldpred2/run_ldpred2.sh#L6, is that the same as this one (unzipped): https://github.com/comorment/containers/blob/deepchocolate/ldpred2/reference/examples/prsice2/Height.gwas.txt.gz? 
If it's not can you push it to this branch?

**Comment by deepchocolate** [comment]
> @deepchocolate , I just have a question: This file `Height.gwas.txt` referenced on line
> 
> https://github.com/comorment/containers/blob/33698fb4bd132eb2c564749712a0bf4c2d1c80fb/tests/ldpred2/run_ldpred2.sh#L6
> 
> , is that the same as this one (unzipped): https://github.com/comorment/containers/blob/deepchocolate/ldpred2/reference/examples/prsice2/Height.gwas.txt.gz?
> If it's not can you push it to this branch?

It should be the same yes!

**Pull request merged**
