### PR TITLE
migrating files from GH/comorment/gwas@47a23f0

### LINKED ISSUE #39: Include Dockerfile and scripts into comorment/containers repo
Currently we use https://github.com/comorment/gwas to keep all *development*-related scripts for comorment containers.
The https://github.com/comorment/containers repo is used to release singularity containers (as .sif files), to keep reference data, and for user documentation. This separation is suboptimal, and it makes more sense to include all development-related scripts (Dockerfile, bash scripts, some dev instuctions, etc) in https://github.com/comorment/containers. However we should keep those codes somewhat hidden from the end user, for example move them to a new ``source`` folder in the root of this repo. After than the github.com/comorment/gwas repo can be archived (e.g. kept in case we need code history, but we lock is so no futher changes can be submitted).

Also, we should change our development model and start using feature & bug-fix branches, using a pull request and code review to integrate changes into the main branch.

### LINKED ISSUE #49: git LFS: files that should have been pointers
A shallow git clone of this repo reports that a few files should've been pointers:
```
 % GIT_LFS_SKIP_SMUDGE=1 /opt/homebrew/bin/git clone --depth 1 git@github.com:comorment/containers.git
Cloning into 'containers'...
remote: Enumerating objects: 1130, done.
remote: Counting objects: 100% (1130/1130), done.
remote: Compressing objects: 100% (1032/1032), done.
remote: Total 1130 (delta 28), reused 1083 (delta 20), pack-reused 0
Receiving objects: 100% (1130/1130), 19.23 MiB | 3.21 MiB/s, done.
Resolving deltas: 100% (28/28), done.
Updating files: 100% (1174/1174), done.
Encountered 5 files that should have been pointers, but weren't:
	usecases/bolt_out/example_3chr.frq
	usecases/bolt_out/example_3chr.log
	usecases/bolt_out/myld.l2.ldscore.gz
	usecases/bolt_out/myld.log
	usecases/saige_out/out_vcf.log
```
Not a big issue though, as they're all pretty small files:
```
 24K	usecases/bolt_out/example_3chr.frq
4.0K	usecases/bolt_out/example_3chr.log
4.0K	usecases/bolt_out/myld.l2.ldscore.gz
4.0K	usecases/bolt_out/myld.log
4.0K	usecases/saige_out/out_vcf.log
```

Edit: Some more info here: https://stackoverflow.com/questions/46704572/git-error-encountered-7-files-that-should-have-been-pointers-but-werent

### PR DESCRIPTION
**Pull request by espenhgn**
Closes #39. 
Closes #49.

### CODE REVIEW

**Review by ofrei — APPROVED** [review]
All changes look very reasonable! Also great to have the tests - I haven't had a chance to try them out right now, but I'll do this next time I build on devbox. For my end it's all OK to merge. Also OK to not include .sif files for now. 

@bayramakdeniz note this doesn't include matlabruntime and enigmaCNV - as we discussed, please put them into separate github repose. I'll do the same for MAGMA & LAVA tools.

One suggestion: consider submitting this commit : https://github.com/comorment/containers/pull/51/commits/cd5be0334901253fc62ba5ddb95b2ac35433d937 on its own, and then square all other changes into a single commit. This way we keep a good overview of the actual changes beyond just moving files over from github.com/precimed/gwas.

**Comment by espenhgn** [comment]
Thanks @ofrei. I'll create a separate PR out of cd5be03, merge that, and squash-merge this PR.

**Review by bayramakdeniz — APPROVED** [review]
Great work Espen, all changes seem quite relevant. Many thanks. I approved

@ofrei , I will move matlabruntime and enigmaCNV to separate repos as we agreed on

**Comment by espenhgn** [comment]
Hi. Turns out #49 is causing me an issue with rebasing all that follows after https://github.com/comorment/containers/commit/cd5be0334901253fc62ba5ddb95b2ac35433d937. I've put this one commit in a separate branch (https://github.com/comorment/containers/tree/commit-cd5be03) and will merge-squash this PR as one commit.

**Pull request merged**
