### PR TITLE
Updated LDpred2 examples

### PR DESCRIPTION
**Pull request by deepchocolate**
Updated LDpred2 documentation to illustrate polygenic scoring with OpenSNP data available in comorment/opensnp repo.

These changes relate to #221

Changes proposed in this pull request:

- Switched data to use in an LDpred2 usage example
- Added a testing script using the opensnp-data

## Before submitting

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [x] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [x] If this PR fixes a bug, I've added a test that will fail without my fix.
- [x] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

### CODE REVIEW

**Comment by deepchocolate** [comment]
@ofrei @espenhgn Just to check before I continue, am I on the right track here with these changes?

**Comment by ofrei** [comment]
@deepchocolate yes :+1:

**Comment by espenhgn** [comment]
Hi @deepchocolate,
Yes, this looks good. 
As per @ofrei's email suggestion, we may choose to have a single directory mount point throughout for the containers, input data, and reference like so:

```
...
export COMORMENT=<path/to/comorment>  # on the host machine
export SINGULARITY_BIND="${COMORMENT}:/comorment"  # perhaps with "read-only" modifier ":ro"
...
export ld_file=/comorment/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr@.rds # as seen by the virtual machine; may need some updates in ldpred2.R defaults
export fileGeno=/comorment/opensnp/opensnp_hm3.bed  
# etc.
```

Thus, we assume that all cloned repos required are put at the same level.

**Comment by deepchocolate** [comment]
@ofrei @espenhgn I think I'm pretty done here... I think there is an option to include `tests/test_LDpred2/scripts/opensnp.sh` script directly in the README, including snippets of produced results. Otherwise I'll convert this to a regular PR.

**Review by espenhgn — APPROVED** [review]
Think this is good to go, with some minor edits I did.  
However, I could not run the example in our dev environment w. 16GB RAM (no swap space) due to lack of memory, so perhaps we can constrict it to use a couple of the smaller chromosomes?

**Comment by deepchocolate** [comment]
> Think this is good to go, with some minor edits I did. However, I could not run the example in our dev environment w. 16GB RAM (no swap space) due to lack of memory, so perhaps we can constrict it to use a couple of the smaller chromosomes?

Yeah, I tend to do most work on my desktop with 64GB of ram, but I've restricted the opensnp script to chromosome 21-22 and that ran fine on my laptop.

Btw, I looked in the `CONTRIBUTING` docs, and I don't find a section named "Writing docstrings" or am I missing it?

**Comment by espenhgn** [comment]
> Btw, I looked in the `CONTRIBUTING` docs, and I don't find a section named "Writing docstrings" or am I missing it?

This was probably omitted for some reason. I'll open a ticket.

**Comment by espenhgn** [comment]
> > Think this is good to go, with some minor edits I did. However, I could not run the example in our dev environment w. 16GB RAM (no swap space) due to lack of memory, so perhaps we can constrict it to use a couple of the smaller chromosomes?
> 
> Yeah, I tend to do most work on my desktop with 64GB of ram, but I've restricted the opensnp script to chromosome 21-22 and that ran fine on my laptop.
> 

I'll do the same in the pgs_toolkit example.

**Pull request merged**
