### PR TITLE
fixes #105 - warning messages in r.sif

### LINKED ISSUE #105: Warning messages during startup of R.sif container
```
During startup - Warning messages:
1: Setting LC_TIME failed, using "C" 
2: Setting LC_MONETARY failed, using "C" 
3: Setting LC_PAPER failed, using "C" 
4: Setting LC_MEASUREMENT failed, using "C" 
```

### PR DESCRIPTION
**Pull request by ofrei**
Fixes #105

Changes proposed in this pull request:
This fix (hack?) is similar to what I did some time ago for regenie tool:
https://github.com/comorment/containers/blob/main/src/dockerfiles/gwas/Dockerfile#L110

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

### CODE REVIEW

**Comment by ofrei** [comment]
I've rebuilt r.sif container, and I think the warnings are gone after this change

**Comment by ofrei** [comment]
@espenhgn thanks! I checked my ``locale``, for some reason I  have an empty ``LC_ALL``. The following setting prior to calling r.sif container solves the issue:
```
export LC_ALL=en_US.UTF-8
```
I'll put that in my ``.bashrc`` file. 

Do you think we should then also remove [this line](https://github.com/comorment/containers/blob/main/src/dockerfiles/gwas/Dockerfile#L110) from ``gwas.sif`` dockerfile?

**Comment by ofrei** [comment]
An alternative fix for me was  to add ``--cleanenv`` to singularity call (https://docs.sylabs.io/guides/3.7/user-guide/environment_and_metadata.html ). It might be good idea to mention this flag in a tutorial.

**Comment by ofrei** [comment]
Not an issue with containers, rather problem in my environment, easy to workaround

**Comment by espenhgn** [comment]
> @espenhgn thanks! I checked my `locale`, for some reason I have an empty `LC_ALL`. The following setting prior to calling r.sif container solves the issue:
> 
> ```
> export LC_ALL=en_US.UTF-8
> ```
> 
> I'll put that in my `.bashrc` file.
> 
> Do you think we should then also remove [this line](https://github.com/comorment/containers/blob/main/src/dockerfiles/gwas/Dockerfile#L110) from `gwas.sif` dockerfile?

Good! It's likely fine to remove that environment variable from the `gwas.sif` build, although I bet it was added for good reasons in the first place. The default in ubuntu 20:04 appears to be unset (checked within the `hello.sif` file invoked with`--cleanenv`):
```
LANG=C
LANGUAGE=
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
```

**Comment by espenhgn** [comment]
@ofrei, can we delete branch https://github.com/comorment/containers/tree/fix105? Seems resolved.

**Pull request closed without merging**
