### PR TITLE
removed redundant LDpred2 example

### LINKED ISSUE #140: LDpred2: remove `/usecases/LDpred2_tutorial` Rmarkdown example
Some of these files (added via #91) now appears quite redundant with the other LDpred2 files in /usecases/LDpred2/. I suggest to remove them.

### PR DESCRIPTION
**Pull request by espenhgn**
Fixes #140 

Changes proposed in this pull request:

- Removed /usecases/LDpred2_tutorial
- Moved tutorial data to /usecases/LDpred2_test/data/ in preparation for https://github.com/comorment/containers/pull/131

## Before submitting

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [x] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.

### CODE REVIEW

**Review by deepchocolate — APPROVED** [review]
Looks good to me!

**Comment by deepchocolate** [comment]
@espenhgn I just realized the `public-data-*` is used by `LDpred2_test/run.sh`, could you instead of removing these files move them to `LDpred2_test/data`?

**Comment by espenhgn** [comment]
> @espenhgn I just realized the `public-data-*` is used by `LDpred2_test/run.sh`, could you instead of removing these files move them to `LDpred2_test/data`?

Sure can do!

**Review by deepchocolate — APPROVED** [review]
Great!

**Comment by espenhgn** [comment]
@deepchocolate, I've moved the data and updated the `run.sh` script where it should function with https://github.com/comorment/containers/pull/131.

**Pull request merged**
