### PR TITLE
`LDpred2`: Removed counting of missing genotypes

### LINKED ISSUE #181: `LDpred2`: Remove time thief
**Is your feature request related to a problem? Please describe.**
I was puzzled by that it took so much time to load the genotype data, and it turns out that it's these lines that seeem to be the culprit: 
https://github.com/comorment/containers/blob/a195c980c3636faad4de4ee8543d7d636cf16bb4/scripts/pgs/LDpred2/ldpred2.R#L139-L140
I've tested commenting these lines out and the time it takes generating PGS for 3 sumstats is down with at least 60%.

**Describe the solution you'd like**
I suggest reming the above lines. What will happen is just that an error will instead appear during the scoring in `snp_ldpred2_inf` or `snp_ldpred2_auto` (something like "you can't have missing values in X"). That's error is maybe not so informative, but it might be possible to capture that error and give more details ("impute data or pass --geno-impute-zero").

### PR DESCRIPTION
**Pull request by deepchocolate**
Fixes #181 

Changes proposed in this pull request:

- Removed countMissingGenotypes as it takes a significant amount of time of total execution time (~60%)
- Clarified exception when there are missing genotypes

## Before submitting

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [x] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [x] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

### CODE REVIEW

**Comment by espenhgn** [comment]
Thanks @deepchocolate; 
Just a preliminary report; some test(s) is failing (ran `git clean -fd .` in the `tests` directory beforehand):
```
$ cd tests && git clean -fd . && cd test_LDpred2
$ bash run.sh
...
Test appending score to output file
Runing unittests on output
-- Failure (???): Appended score output ----------------------------------------
hasAllColumns(tmp, cnamesExp) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
Expected columns FID,IID,score,newScore but FID,IID,score were found in /nrec/space/espenh/containers/tests/test_LDpred2/output/public-data.score.inf

-- Failure (???): Appended score output ----------------------------------------
file.exists(filePlot) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
Diagnostic plot was not found: /nrec/space/espenh/containers/tests/test_LDpred2/output/newScore.png

Error in reporter$stop_if_needed() : Test failed
Calls: test_that -> <Anonymous>
Execution halted
```
Can you reproduce it on your end?

I've updated the version and stuff for the next release.

**Comment by deepchocolate** [comment]
> Thanks @deepchocolate; Just a preliminary report; some test(s) is failing (ran `git clean -fd .` in the `tests` directory beforehand):
> 
> ```
> $ cd tests && git clean -fd . && cd test_LDpred2
> $ bash run.sh
> ...
> Test appending score to output file
> Runing unittests on output
> -- Failure (???): Appended score output ----------------------------------------
> hasAllColumns(tmp, cnamesExp) is not TRUE
> 
> `actual`:   FALSE
> `expected`: TRUE 
> Expected columns FID,IID,score,newScore but FID,IID,score were found in /nrec/space/espenh/containers/tests/test_LDpred2/output/public-data.score.inf
> 
> -- Failure (???): Appended score output ----------------------------------------
> file.exists(filePlot) is not TRUE
> 
> `actual`:   FALSE
> `expected`: TRUE 
> Diagnostic plot was not found: /nrec/space/espenh/containers/tests/test_LDpred2/output/newScore.png
> 
> Error in reporter$stop_if_needed() : Test failed
> Calls: test_that -> <Anonymous>
> Execution halted
> ```
> 
> Can you reproduce it on your end?
> 
> I've updated the version and stuff for the next release.

Are you sure this is not a memory issue again? Because when I ran it, it stopped  at the change in `scripts/extended.sh`, it should stop there if it doesn't receive an error. Don't know why I changed that.

When I fixed that and removed all output files all test passed

**Comment by espenhgn** [comment]
Yes, I think it is due to lack of memory (during `Loading LD reference from /ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr@.rds LD_with_blocks_chr1.rds : loading LD for 3495 out of 117534 SNPs`, but the reason is not captured). 
Will check with @ofrei what we can do to upgrade the specs to 16GB of RAM for this VM we're using.
I'm fine with merging as is until that is resolved.

**Review by espenhgn — APPROVED** [review]

**Comment by deepchocolate** [comment]
> Yes, I think it is due to lack of memory (during `Loading LD reference from /ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr@.rds LD_with_blocks_chr1.rds : loading LD for 3495 out of 117534 SNPs`, but the reason is not captured). Will check with @ofrei what we can do to upgrade the specs to 16GB of RAM for this VM we're using. I'm fine with merging as is until that is resolved.

I'm guessing the system terminates the execution somehow so that there's no error returned
Just going to switch back the exit code in `extended.sh` and then I'll merge

**Pull request merged**
